[package]
name = "conecta-core"
version = "0.1.0"
edition = "2021"

[dependencies]
peak_alloc = "0.3.0"
log = "0.4.27"
env_logger = "0.11.8"

arrow = { version = "55.2.0", features = ["prettyprint", "ffi"] }

r2d2_postgres = "0.18.2"
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
sqlparser = "0.57.0"
rayon = "1.10.0"
chrono = "0.4.41"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
flamegraph = "0.6.8"
